.\" Hey, EMACS: -*- nroff -*-
.TH WEATHER 1 "04 Sep 2018"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
Weather
.SH SYNOPSIS
.B Weather
.SH DESCRIPTION
.B Weather
It is used to display weather information.
.PP
.SH SEE ALSO
.BR weather (1),
.br
.SH AUTHOR
weather was written by lixiang <lixiang@kylinos.cn>.
.PP
This manual page was written by lixiang <lixiang@kylinos.cn>.
